version: "2.4"
services:
  broker:
    ports:
      - 1883:1883
      - 8883:1883
    build:
      context: .
      dockerfile: MQTTBroker/Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - mariadb
  api:
    ports:
      - 80:8393
      - 443:8394
    build:
      context: .
      dockerfile: MQTTAPI/Dockerfile
    depends_on:
      - mariadb
  mariadb:
      image: lscr.io/linuxserver/mariadb:latest
      expose:
        - 3306
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: "super-secret-root-password"
        MYSQL_DATABASE: "IntelliHouse"
        MYSQL_USER: "IntelliHouse-User"
        MYSQL_PASSWORD: "P@ssw0rd"
